"""导入模拟岗位数据（模拟从招聘平台扫描到的结果）"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))

from job_hunt.db.database import Database
from job_hunt.models.job import Job

# 模拟从 GXRC / 51job / BOSS / 桂聘网 扫描到的岗位
jobs = [
    # 环境工程对口
    Job(
        title="环境工程师",
        company="广西环科院",
        city="南宁",
        platform="gxrc",
        source_id="gxrc_001",
        source_url="https://s.gxrc.com/jobDetail?id=001",
        salary_min=6000, salary_max=9000,
        salary_text="6-9K",
        experience="1-3年",
        education="本科",
        tags="环境工程,环评,监测",
        description="负责建设项目环境影响评价报告编制，开展环境监测与数据分析。要求环境工程/环境科学相关专业本科及以上学历，熟悉环评导则与AERMOD模型优先。",
        requirements="环境工程本科，1-3年环评经验，熟悉AERMOD",
    ),
    Job(
        title="环保工程师",
        company="广西绿源环保科技",
        city="南宁",
        platform="gxrc",
        source_id="gxrc_002",
        source_url="https://s.gxrc.com/jobDetail?id=002",
        salary_min=7000, salary_max=10000,
        salary_text="7-10K",
        experience="1年",
        education="本科",
        tags="环保,废气处理,监测",
        description="负责企业废气、废水处理设施运维，开展环境监测数据采集与分析。要求环境工程专业，熟悉Python数据分析者优先。",
        requirements="环境工程本科，可接受应届",
    ),
    Job(
        title="环境监测分析师",
        company="广西生态环境监测中心",
        city="南宁",
        platform="boss",
        source_id="boss_001",
        source_url="https://www.zhipin.com/job/001",
        salary_min=8000, salary_max=12000,
        salary_text="8-12K",
        experience="不限",
        education="本科",
        tags="环境监测,数据分析,AQI",
        description="负责大气环境质量监测数据分析与报告编制，建立空气质量预测模型。要求环境/统计/计算机相关专业，掌握Python/pandas数据处理。",
        requirements="环境或数据相关专业本科，Python数据处理",
    ),
    Job(
        title="环境影响评价工程师",
        company="桂林环保咨询",
        city="桂林",
        platform="gxrc",
        source_id="gxrc_003",
        source_url="https://s.gxrc.com/jobDetail?id=003",
        salary_min=7000, salary_max=11000,
        salary_text="7-11K",
        experience="1-3年",
        education="本科",
        tags="环评,大气,AERMOD",
        description="编制环境影响评价报告，开展大气环境质量现状监测与扩散模拟。熟悉AERMOD、环评导则优先。",
        requirements="环境工程本科，环评经验优先",
    ),
    # 数据分析方向（交叉）
    Job(
        title="数据分析师（环境数据）",
        company="广西新美数据有限公司",
        city="南宁",
        platform="boss",
        source_id="boss_002",
        source_url="https://www.zhipin.com/job/002",
        salary_min=9000, salary_max=14000,
        salary_text="9-14K",
        experience="1-3年",
        education="本科",
        tags="Python,pandas,SQL,数据分析",
        description="负责环境/气象数据的清洗、分析与可视化，构建数据看板。要求熟练Python、pandas、SQL，有环境或气象数据经验优先。",
        requirements="本科，Python+SQL，1-3年",
    ),
    Job(
        title="Python数据分析师",
        company="广西景耀网络科技",
        city="南宁",
        platform="boss",
        source_id="boss_003",
        source_url="https://www.zhipin.com/job/003",
        salary_min=10000, salary_max=15000,
        salary_text="10-15K",
        experience="1-3年",
        education="本科",
        tags="Python,数据分析,可视化",
        description="使用Python进行业务数据分析，搭建数据可视化报表。熟悉pandas、numpy、matplotlib。",
        requirements="本科，Python数据分析1-3年",
    ),
    # Python 开发方向
    Job(
        title="Python开发工程师",
        company="广西东科宁创装备",
        city="南宁",
        platform="boss",
        source_id="boss_004",
        source_url="https://www.zhipin.com/job/004",
        salary_min=9000, salary_max=13000,
        salary_text="9-13K",
        experience="1-3年",
        education="本科",
        tags="Python,Flask,后端",
        description="使用Python(Flask/Django)开发公司内部信息化系统，参与环保设备数据采集平台后端开发。",
        requirements="本科，Python+Flask，1-3年",
    ),
    Job(
        title="软件开发工程师（环保信息化）",
        company="广西环境信息中心",
        city="南宁",
        platform="gxrc",
        source_id="gxrc_004",
        source_url="https://s.gxrc.com/jobDetail?id=004",
        salary_min=8000, salary_max=12000,
        salary_text="8-12K",
        experience="不限",
        education="本科",
        tags="Python,信息化,环境",
        description="负责环保信息化平台开发维护，对接环境监测数据接口。环境工程+编程能力复合背景优先。",
        requirements="本科，Python，可接受应届",
    ),
    # 广东方向
    Job(
        title="环境数据工程师",
        company="广州绿创环境科技",
        city="广州",
        platform="boss",
        source_id="boss_005",
        source_url="https://www.zhipin.com/job/005",
        salary_min=12000, salary_max=18000,
        salary_text="12-18K",
        experience="1-3年",
        education="本科",
        tags="环境,Python,数据,PM2.5",
        description="负责大气污染源解析与空气质量建模，使用Python处理PM2.5监测数据。环境工程+数据能力优先。",
        requirements="本科，环境或数据相关，Python",
    ),
    Job(
        title="大气环境研究助理",
        company="华南环境科学研究所",
        city="广州",
        platform="boss",
        source_id="boss_006",
        source_url="https://www.zhipin.com/job/006",
        salary_min=10000, salary_max=14000,
        salary_text="10-14K",
        experience="不限",
        education="硕士",
        tags="大气,PM2.5,研究",
        description="参与大气污染防治研究项目，开展PM2.5源解析、AQI时空分析。环境/气象专业优先。",
        requirements="硕士优先，环境或气象专业",
    ),
    # 应过滤的岗位
    Job(
        title="猎头顾问-环境行业",
        company="XX猎头公司",
        city="南宁",
        platform="boss",
        source_id="boss_007",
        source_url="https://www.zhipin.com/job/007",
        salary_min=5000, salary_max=8000,
        salary_text="5-8K",
        experience="不限",
        education="本科",
        tags="猎头,招聘",
        description="为环境行业客户招聘中高端人才，底薪+提成。",
        requirements="本科，沟通能力强",
    ),
    Job(
        title="Python培训 学徒 包就业",
        company="某培训机构",
        city="南宁",
        platform="boss",
        source_id="boss_008",
        source_url="https://www.zhipin.com/job/008",
        salary_min=0, salary_max=0,
        salary_text="培训补贴",
        experience="不限",
        education="不限",
        tags="培训,学徒",
        description="零基础Python培训，包就业，学费可分期。",
        requirements="不限",
    ),
    # 民企（薪资偏低，测试过滤）
    Job(
        title="环境监测员",
        company="南宁某小型检测站",
        city="南宁",
        platform="guipin",
        source_id="guipin_001",
        source_url="https://www.guipin.com/job/001",
        salary_min=3500, salary_max=4500,
        salary_text="3.5-4.5K",
        experience="不限",
        education="大专",
        tags="监测,采样",
        description="负责水质、大气样品采集与简单检测。",
        requirements="大专以上，可接受应届",
    ),
]

db = Database()
saved = 0
for j in jobs:
    jid = db.save_job(j)
    if jid > 0:
        saved += 1
        print(f"  [OK] {j.platform} | {j.title} @ {j.company} ({j.city}) {j.salary_text}")

print(f"\n共导入 {saved} 个岗位")
print(f"数据库岗位总数: {db.get_job_count()}")
